# ruff: noqa: E501
"""Proyecto de ejemplo con evidencias en castellano para el sistema de control de acceso por reconocimiento facial."""

SAMPLE_PROJECT_ES = {
    "name": "Proyecto de Ejemplo — Control de Acceso por Reconocimiento Facial",
    "description": (
        "Sistema de IA que utiliza reconocimiento facial para controlar el acceso "
        "físico a edificios de oficinas corporativas en la UE. Captura imágenes "
        "faciales mediante cámaras de seguridad en puntos de entrada, las compara "
        "con la base de datos de empleados registrados y concede o deniega el acceso "
        "en tiempo real. Procesamiento de datos biométricos con clasificación de "
        "riesgo alto, ~2.000 empleados por sede, operación 24/7."
    ),
    "risk_classification": "high",
    "intended_purpose": (
        "Autenticar empleados mediante reconocimiento facial en puntos de acceso "
        "de edificios corporativos para conceder o denegar la entrada física en "
        "tiempo real, sustituyendo tarjetas de acceso tradicionales."
    ),
    "intended_users": (
        "Personal de seguridad física, administradores de sistemas de control de "
        "acceso y responsables de instalaciones de oficinas corporativas en la UE."
    ),
    "deployment_context": (
        "Edificios de oficinas corporativas en la Unión Europea, con cámaras en "
        "tornos y puertas de acceso. Operación continua 24/7, aproximadamente "
        "2.000 empleados por sede."
    ),
    "questionnaire_answers": {
        "q1": "yes",
        "q2": "yes",
        "q3": ["none"],
        "q4": ["none"],
        "q5": "no",
        "q6": ["biometrics"],
        "q7": "yes",
        "q8": "no",
        "q9": ["none"],
        "q10": "no",
        "q11": "yes-bias",
        "q12": "on-the-loop",
        "q13": "no",
        "q14": "no",
        "q15": "no",
        "q16": "no",
        "q17": "no",
    },
}

SAMPLE_EVIDENCE_ES: dict[str, str] = {
    # ── Cybersecurity (Article 15) ──────────────────────────────────────
    "cybersecurity-CYB-01-0": "Los conjuntos de datos de plantillas faciales están protegidos con sumas de verificación SHA-256 y control de acceso basado en roles para evitar manipulaciones.",
    "cybersecurity-CYB-01-1": "Las imágenes faciales incorporadas durante el registro de empleados se verifican mediante firmas criptográficas y validación de procedencia.",
    "cybersecurity-CYB-02-0": "Se realizan pruebas adversariales trimestrales con imágenes manipuladas, máscaras y deepfakes para evaluar la resistencia del modelo.",
    "cybersecurity-CYB-02-1": "Se aplican técnicas de detección de vida (liveness detection) y anti-spoofing para mantener el rendimiento frente a ataques de presentación.",
    "cybersecurity-CYB-03-0": "Se aplican filtros de validación de entrada en las imágenes capturadas para rechazar fotografías impresas, pantallas y otros vectores de inyección.",
    "cybersecurity-CYB-04-0": "Los pesos del modelo de reconocimiento facial se almacenan cifrados con AES-256 en un módulo HSM con acceso restringido a dos administradores.",
    "cybersecurity-CYB-05-0": "El sistema no expone datos biométricos en sus respuestas; solo devuelve decisiones binarias de acceso concedido o denegado sin plantillas faciales.",
    "cybersecurity-CYB-06-0": "Las bibliotecas de visión por computador y las dependencias de contenedores se escanean semanalmente con Trivy y Dependabot.",
    "cybersecurity-CYB-07-0": "Se aplica IAM con segregación de roles: solo el equipo de seguridad accede a las plantillas biométricas y el equipo de operaciones gestiona las API de acceso.",
    "cybersecurity-CYB-08-0": "El entorno de inferencia opera en una red aislada con WAF, proxy inverso y reglas de cortafuegos que restringen el tráfico a los tornos autorizados.",
    "cybersecurity-CYB-09-0": "Cada evento de acceso genera un registro inmutable en un sistema SIEM centralizado, incluyendo marca temporal, cámara y resultado de la decisión.",
    "cybersecurity-CYB-10-0": "Las plantillas biométricas se cifran en reposo con AES-256 y en tránsito con TLS 1.3 entre cámaras, servidor de inferencia y base de datos.",
    "cybersecurity-CYB-11-0": "Se ejecuta análisis de vulnerabilidades mensual y gestión de parches sobre los endpoints de la API, contenedores y servidores de inferencia.",
    # ── Documentation (Article 11, Annex IV) ────────────────────────────
    "documentation-MG01-0": "Se definió una estrategia de documentación técnica en la fase de diseño, cubriendo arquitectura del modelo facial, datos de entrenamiento y despliegue.",
    "documentation-MG01-1": "El plan incluye hitos trimestrales y asigna responsables de ingeniería, seguridad y cumplimiento para garantizar la trazabilidad.",
    "documentation-MG02-0": "Existe un calendario semestral de revisión de la documentación técnica del sistema de reconocimiento facial.",
    "documentation-MG02-1": "El calendario contempla actualizaciones por cambios normativos del Reglamento de IA, mejoras del modelo o modificaciones operativas.",
    "documentation-MG03-0": "Se utiliza Git para el control de versiones de toda la documentación técnica, con ramas protegidas y revisiones obligatorias.",
    "documentation-MG03-1": "Cada cambio en el sistema de reconocimiento facial activa automáticamente un ticket de actualización de la documentación correspondiente.",
    "documentation-MG04-0": "Se ha establecido un plan de comunicación interna mediante boletines trimestrales dirigidos a seguridad, TI, RRHH y dirección.",
    "documentation-MG04-1": "Se realizaron sesiones informativas para que todas las áreas comprendan el propósito de la documentación técnica y su relación con sus funciones.",
    "documentation-MG05-0": "Se ha designado formalmente un responsable de documentación técnica con autoridad transversal para coordinar su preparación y supervisión.",
    "documentation-MG05-1": "El responsable dispone de formación en IA biométrica, acceso a todos los repositorios y dedicación parcial garantizada para esta tarea.",
    "documentation-MG06-0": "Se han asignado responsables específicos de documentación para datos biométricos, seguridad, riesgos e infraestructura del sistema.",
    "documentation-MG06-1": "Los responsables designados tienen competencias técnicas acreditadas en sus respectivos dominios mediante certificaciones o experiencia documentada.",
    "documentation-MG07-0": "Toda la documentación técnica se almacena en un repositorio Confluence protegido con autenticación SSO y copias de seguridad diarias.",
    "documentation-MG07-1": "El sistema de gestión documental permite control de versiones, permisos de acceso por rol y auditorías de acceso completas.",
    "documentation-MG08-0": "Se ha verificado que todos los responsables tienen acceso adecuado al sistema de gestión documental según su perfil.",
    "documentation-MG08-1": "Las políticas de acceso están diferenciadas por roles: lectura para operadores, edición para ingenieros, administración para el responsable de documentación.",
    "documentation-MG09-0": "Se realizan copias de seguridad cifradas diarias de la documentación, con redundancia geográfica en dos centros de datos de la UE.",
    "documentation-MG09-1": "Se ejecutan auditorías trimestrales para verificar la integridad y disponibilidad de las copias de seguridad de la documentación.",
    "documentation-MG10-0": "Los responsables de despliegue tienen acceso directo a las instrucciones de instalación, configuración de cámaras y calibración del sistema.",
    "documentation-MG10-1": "Semestralmente se valida que la documentación de despliegue es actual, comprensible y completa desde el punto de vista operativo.",
    "documentation-MG11-0": "Existe un procedimiento de actualización periódica de las instrucciones de despliegue tras cada nueva versión del modelo facial.",
    "documentation-MG11-1": "Los responsables de despliegue reciben notificación automática por correo cuando se modifican las instrucciones de instalación.",
    "documentation-MG12-0": "Se han definido auditorías anuales de la documentación técnica con criterios de trazabilidad, vigencia y accesibilidad.",
    "documentation-MG12-1": "Las auditorías incluyen verificaciones de trazabilidad de versiones, actualidad del contenido y accesibilidad para los perfiles autorizados.",
    "documentation-MG13-0": "Se ha realizado una identificación de normas armonizadas aplicables, incluyendo ISO/IEC 42001, ISO 27001 y normas de biometría ISO 30107.",
    "documentation-MG13-1": "Se realiza un seguimiento semestral de cambios normativos que puedan afectar al cumplimiento del sistema de reconocimiento facial.",
    "documentation-MG14-0": "Se ha evaluado la posibilidad de obtener certificaciones ISO 27001 e ISO/IEC 42001 para el sistema de IA biométrica.",
    "documentation-MG14-1": "Se dispone de evidencia documental del cumplimiento de los criterios exigidos por la certificación ISO 27001 vigente.",
    "documentation-MG15-0": "El repositorio garantiza almacenamiento seguro y duradero durante un mínimo de 10 años con cifrado y control de acceso.",
    "documentation-MG15-1": "El sistema permite acceso inmediato a la documentación por parte de autoridades nacionales competentes cuando sea requerido.",
    "documentation-MG16-0": "La documentación del SGC se ha incluido en el repositorio oficial de conservación con etiquetado y clasificación adecuados.",
    "documentation-MG16-1": "Se asegura su disponibilidad durante al menos 10 años y su accesibilidad para las autoridades competentes.",
    "documentation-MG17-0": "Las aprobaciones de organismos notificados y evidencias de cambios se conservan en un repositorio centralizado y seguro.",
    "documentation-MG17-1": "El plan contempla la conservación de estos documentos durante un mínimo de 10 años.",
    "documentation-MG18-0": "El sistema contempla la conservación de decisiones y documentos emitidos por organismos notificados en el repositorio central.",
    "documentation-MG18-1": "Se asegura la conservación y el acceso durante al menos 10 años en un repositorio adecuado con controles de integridad.",
    "documentation-MG19-0": "La declaración de conformidad se archiva en el repositorio oficial con garantía de disponibilidad y conservación durante al menos 10 años.",
    "documentation-MG20-0": "Se han establecido auditorías anuales del mecanismo de conservación de la documentación técnica del sistema biométrico.",
    "documentation-MG20-1": "Se verifica el correcto funcionamiento y el cumplimiento de las obligaciones de conservación en cada auditoría programada.",
    "documentation-MG21-0": "Se ha contratado un servicio de custodia documental que garantiza el acceso continuado incluso si el proveedor cesa su actividad.",
    "documentation-MG21-1": "Se han adoptado medidas legales y técnicas, incluyendo cláusulas contractuales de continuidad, para asegurar la disponibilidad futura.",
    "documentation-MG22-0": "La documentación incluye el propósito del sistema, nombre del proveedor, versión del modelo y fecha de la última actualización.",
    "documentation-MG22-1": "Se indica la trazabilidad entre la versión anterior y la actual del modelo facial, incluyendo registro de cambios.",
    "documentation-MG23-0": "Se ha documentado cómo el sistema se comunica con los tornos físicos, el directorio de empleados y el sistema de alarmas.",
    "documentation-MG23-1": "Se han documentado los requisitos de compatibilidad y protocolos de comunicación para garantizar la interoperabilidad con sistemas de acceso.",
    "documentation-MG24-0": "Se registran las versiones del modelo facial utilizadas y los procedimientos necesarios para actualizaciones o parches de seguridad.",
    "documentation-MG24-1": "Se indica la política de actualizaciones planificada para mantener la seguridad y funcionalidad del sistema de reconocimiento.",
    "documentation-MG25-0": "Se detalla la forma de distribución del sistema: servicio on-premise desplegado en contenedores Docker en cada edificio.",
    "documentation-MG25-1": "Se proporciona documentación clara para la puesta en servicio en cada sede, incluyendo configuración de cámaras y red local.",
    "documentation-MG26-0": "Se ha documentado el hardware necesario: GPUs de inferencia, cámaras IR de alta resolución y servidores de procesamiento de borde.",
    "documentation-MG26-1": "Se especifican las posibles limitaciones con determinados modelos de cámara y requisitos mínimos de resolución e iluminación.",
    "documentation-MG27-0": "Se incluyen imágenes de las cámaras instaladas, diagramas de ubicación en tornos y capturas del panel de administración.",
    "documentation-MG27-1": "Las ilustraciones están correctamente asociadas con las descripciones técnicas de cada componente del sistema de acceso.",
    "documentation-MG28-0": "La documentación contiene una descripción completa de la interfaz de usuario del panel de seguridad utilizado por los operadores.",
    "documentation-MG28-1": "Se incluyen capturas de pantalla y diagramas de flujo para familiarizar al operador con la interfaz de gestión.",
    "documentation-MG29-0": "Se incluyen instrucciones prácticas actualizadas para la instalación de cámaras, calibración y puesta en marcha del sistema.",
    "documentation-MG29-1": "Las instrucciones contemplan errores frecuentes durante el despliegue y las acciones correctivas correspondientes.",
    "documentation-MG30-0": "Se han documentado las bibliotecas de visión por computador y modelos preentrenados utilizados, incluyendo licencias y modificaciones.",
    "documentation-MG30-1": "Se han evaluado y documentado los riesgos derivados del uso de modelos de terceros para el reconocimiento facial.",
    "documentation-MG31-0": "Se han documentado todos los elementos de diseño técnico, incluyendo la arquitectura CNN utilizada y los algoritmos de comparación facial.",
    "documentation-MG31-1": "Se registran las concesiones técnicas realizadas, como el umbral de confianza seleccionado y su impacto en falsos positivos y negativos.",
    "documentation-MG32-0": "Se incluye un esquema de arquitectura del sistema con la interacción entre cámaras, servidor de inferencia, base de datos y tornos.",
    "documentation-MG32-1": "Se describen los recursos computacionales empleados en cada fase: GPUs para entrenamiento y servidores de inferencia en producción.",
    "documentation-MG33-0": "Se han documentado los datos de entrenamiento (imágenes faciales de empleados), las metodologías de test y los conjuntos de validación.",
    "documentation-MG33-1": "Se dispone de evidencia del control de calidad de datos, incluyendo limpieza de imágenes duplicadas y verificación de etiquetas.",
    "documentation-MG34-0": "Se han evaluado las medidas de supervisión humana: un operador de seguridad puede verificar visualmente cada decisión de acceso.",
    "documentation-MG34-1": "La documentación incluye el panel de supervisión donde el operador puede comparar la imagen capturada con la plantilla registrada.",
    "documentation-MG35-0": "Se han documentado los cambios planificados, como actualización del modelo base y ampliación a nuevas sedes, y su impacto técnico.",
    "documentation-MG35-1": "Se especifican procedimientos de validación para garantizar que los cambios no comprometan la conformidad ni la precisión del sistema.",
    "documentation-MG36-0": "Se conservan evidencias firmadas de las pruebas realizadas: tests de precisión, tests de sesgo demográfico y tests de rendimiento.",
    "documentation-MG36-1": "Se incluyen pruebas específicas para verificar el impacto de cada actualización del modelo en la tasa de reconocimiento.",
    "documentation-MG37-0": "Se detallan las medidas de ciberseguridad: cifrado AES-256, TLS 1.3, aislamiento de red y control de acceso basado en roles.",
    "documentation-MG37-1": "La documentación incluye evaluaciones de vulnerabilidades realizadas y mecanismos de gestión de incidentes de seguridad.",
    "documentation-MG38-0": "Se identifican y documentan los riesgos potenciales: falsos positivos que permiten acceso no autorizado, sesgo demográfico y filtración de datos biométricos.",
    "documentation-MG38-1": "La documentación incluye mecanismos de mitigación y supervisión de riesgos durante todo el ciclo de vida del sistema.",
    "documentation-MG39-0": "Se especifican las funciones del operador de seguridad: supervisión del panel, gestión de excepciones y escalado de incidencias.",
    "documentation-MG39-1": "Se describe la formación requerida para que el operador interprete correctamente los resultados de confianza del sistema.",
    "documentation-MG40-0": "Se justifican los parámetros de rendimiento: tasa de acierto ≥99,5%, tiempo de respuesta <2 segundos, tasa de falso rechazo <0,5%.",
    "documentation-MG40-1": "Estos parámetros han sido validados en pruebas documentadas con conjuntos de datos representativos de la población de empleados.",
    "documentation-MG41-0": "Se ha documentado un sistema de gestión de riesgos conforme al Artículo 9, cubriendo todos los riesgos del sistema biométrico.",
    "documentation-MG41-1": "Se especifica cómo se actualiza el sistema de riesgos ante cambios relevantes en el ciclo de vida del sistema de IA.",
    "documentation-MG42-0": "Se ha registrado el historial de cambios relevantes del sistema desde el diseño inicial hasta la versión actual en producción.",
    "documentation-MG42-1": "Se indica el impacto de cada cambio sobre la seguridad, la precisión y el cumplimiento normativo del sistema.",
    "documentation-MG43-0": "Se especifican las normas armonizadas seguidas: ISO/IEC 42001, ISO 30107 (anti-spoofing) e ISO 27001 (seguridad de la información).",
    "documentation-MG43-1": "Se justifican adecuadamente las soluciones adoptadas en los casos donde no se aplican normas armonizadas específicas.",
    "documentation-MG44-0": "Se ha incluido una copia válida de la declaración de conformidad del sistema en la documentación técnica.",
    "documentation-MG44-1": "Se verifica que la declaración está firmada por el proveedor autorizado y referencia explícitamente el Artículo 47 del Reglamento.",
    "documentation-MG45-0": "Se ha definido un sistema de evaluación del rendimiento del sistema facial tras su despliegue comercial en cada sede.",
    "documentation-MG45-1": "El plan de vigilancia poscomercialización contempla mecanismos de recogida de información, auditorías y mejoras continuas.",
    # ── QMS (Article 17) ────────────────────────────────────────────────
    "qms-QMS-01-0": "Se ha definido una estrategia de cumplimiento normativo que cubre el Reglamento de IA de la UE para el sistema de reconocimiento facial.",
    "qms-QMS-01-1": "La estrategia establece hitos de cumplimiento trimestrales alineados con las fechas de entrada en vigor del Reglamento.",
    "qms-QMS-02-0": "Se han definido técnicas y procedimientos sistemáticos para el diseño, control y verificación del modelo de reconocimiento facial.",
    "qms-QMS-03-0": "Los procedimientos de desarrollo incluyen revisión de código obligatoria, control de calidad automatizado y validación de modelos.",
    "qms-QMS-04-0": "Se realizan pruebas de validación antes, durante y después del desarrollo, incluyendo tests de precisión y sesgo demográfico.",
    "qms-QMS-04-1": "Las métricas y umbrales están documentados: precisión ≥99,5%, tasa de falsos positivos <0,01%, sesgo demográfico <2% de diferencia.",
    "qms-QMS-05-0": "Se han documentado las especificaciones técnicas aplicables, incluyendo ISO 30107 para detección de ataques de presentación.",
    "qms-QMS-06-0": "Existen procedimientos documentados para la adquisición, almacenamiento, etiquetado y retención de imágenes faciales de empleados.",
    "qms-QMS-07-0": "El sistema de gestión de riesgos biométricos está integrado en el sistema de gestión de calidad de la organización.",
    "qms-QMS-08-0": "Se ha establecido un sistema de vigilancia poscomercialización que monitoriza la precisión y el rendimiento del sistema en producción.",
    "qms-QMS-09-0": "Se han definido procedimientos para la notificación de incidentes graves, como accesos no autorizados por falsos positivos.",
    "qms-QMS-10-0": "Existen procedimientos de comunicación con las autoridades nacionales competentes y la autoridad de protección de datos.",
    "qms-QMS-11-0": "Se dispone de sistemas para el mantenimiento de registros de acceso, registros técnicos y documentación del modelo.",
    "qms-QMS-12-0": "El SGC incluye procedimientos de gestión de recursos, incluyendo aprovisionamiento de GPUs y cámaras de repuesto.",
    "qms-QMS-13-0": "Se ha establecido un marco de responsabilidades que define las funciones de los equipos de desarrollo, despliegue y operaciones.",
    "qms-QMS-14-0": "El SGC es proporcional al tamaño de la organización y al riesgo alto que supone el procesamiento de datos biométricos.",
    "qms-QMS-15-0": "Se aplican validaciones estadísticas y pruebas de sobreajuste, incluyendo validación cruzada k-fold, durante el entrenamiento del modelo facial.",
    "qms-QMS-16-0": "Existe un procedimiento formal para gestionar modificaciones sustanciales del sistema, incluyendo la necesidad de nueva evaluación de conformidad.",
    # ── Incidents (Article 73) ──────────────────────────────────────────
    "incidents-M-INC-01-0": "El proveedor ha definido procedimientos de notificación de incidentes graves integrados en el SGC, cubriendo accesos no autorizados por fallos del modelo.",
    "incidents-M-INC-01-1": "El responsable del despliegue dispone de procedimientos para notificar incidentes graves como accesos indebidos o fallos sistemáticos.",
    "incidents-M-INC-02-0": "El proveedor mantiene un documento actualizado con los datos de contacto del responsable ante la Autoridad de Vigilancia del Mercado.",
    "incidents-M-INC-02-1": "El responsable del despliegue tiene acceso al documento con el contacto de la Autoridad de Vigilancia del Mercado.",
    "incidents-M-INC-03-0": "El proveedor ha preparado un manual de usuario para el canal de gestión de solicitudes e incidencias entre desplegador y proveedor.",
    "incidents-M-INC-03-1": "El responsable del despliegue tiene acceso al manual de usuario del canal de gestión de incidencias con el proveedor.",
    "incidents-M-INC-04-0": "El proveedor ha preparado un documento que explica la clasificación del sistema como alto riesgo según el Reglamento de IA.",
    "incidents-M-INC-04-1": "El responsable del despliegue tiene acceso al documento que clasifica el sistema de reconocimiento facial según el Reglamento.",
    "incidents-M-INC-05-0": "El proveedor dispone de documentación acreditativa del conocimiento sobre los derechos fundamentales de la Unión Europea.",
    "incidents-M-INC-05-1": "El responsable del despliegue dispone de documentación acreditativa del conocimiento sobre los derechos fundamentales de la UE.",
    # ── Risk Management (Article 9) ─────────────────────────────────────
    "risk-management-MG01-0": "Se ha definido un sistema de gestión de riesgos para el sistema biométrico de alto riesgo a lo largo de todo su ciclo de vida.",
    "risk-management-MG01-1": "Se han identificado y documentado los elementos del contexto interno y externo de la organización relevantes para el sistema biométrico.",
    "risk-management-MG01-2": "La dirección ha formalizado su liderazgo y compromiso con la gestión de riesgos mediante políticas, procedimientos y asignación de recursos.",
    "risk-management-MG02-0": "Se ha definido y actualizado el apetito de riesgo en relación con el impacto del sistema biométrico en la salud, seguridad y derechos fundamentales.",
    "risk-management-MG03-0": "Se han identificado, inventariado y documentado todos los componentes del sistema: cámaras, modelo facial, base de datos biométrica y tornos.",
    "risk-management-MG04-0": "Se han identificado todos los riesgos asociados: sesgo demográfico, falsos positivos, filtración de datos biométricos y fallos de hardware.",
    "risk-management-MG05-0": "Todos los riesgos identificados se han analizado y evaluado asignando probabilidad de ocurrencia e impacto sobre derechos fundamentales.",
    "risk-management-MG06-0": "Se ha evaluado que el sistema no se utiliza con menores de 18 años, ya que el acceso se limita a empleados adultos registrados.",
    "risk-management-MG07-0": "Se han definido mecanismos de comunicación y consulta con las partes interesadas sobre el sistema de gestión de riesgos biométricos.",
    "risk-management-MG08-0": "Se han considerado los riesgos relacionados con la vigilancia poscomercialización, incluyendo degradación del modelo y cambios en la población.",
    "risk-management-MG09-0": "Se han definido y priorizado las opciones de tratamiento de riesgos según criterios de eficacia y viabilidad para el sistema facial.",
    "risk-management-MG09-1": "Se han evaluado medidas de mitigación adecuadas para cada riesgo identificado, incluyendo umbrales de confianza ajustables.",
    "risk-management-MG10-0": "Se han determinado todas las opciones de tratamiento para los riesgos identificados, analizados y evaluados del sistema biométrico.",
    "risk-management-MG11-0": "El sistema de gestión de riesgos se ha implementado a lo largo de todo el ciclo de vida del sistema de reconocimiento facial.",
    "risk-management-MG11-1": "El sistema de gestión de riesgos se mantiene de forma continua con revisiones trimestrales y actualizaciones ante cambios relevantes.",
    "risk-management-MG11-2": "Se ha planificado la implementación de las medidas de tratamiento definidas con plazos y responsables asignados.",
    "risk-management-MG12-0": "Se ha definido e implementado un proceso de monitorización y mejora continua del sistema de gestión de riesgos biométricos.",
    "risk-management-MG12-1": "Se han establecido procedimientos de prueba para garantizar que el sistema cumple su propósito previsto de control de acceso.",
    "risk-management-MG12-2": "Se han establecido procedimientos de prueba para garantizar que se cumplen los requisitos de los sistemas de IA de alto riesgo.",
    "risk-management-MG12-3": "Se han definido e implementado pruebas en condiciones reales con empleados voluntarios en una sede piloto.",
    "risk-management-MG13-0": "Se han establecido períodos de revisión trimestrales y de monitorización continua del sistema de gestión de riesgos.",
    "risk-management-MG14-0": "El sistema de gestión de riesgos se ha documentado a lo largo de todo el ciclo de vida del sistema biométrico.",
    "risk-management-MG14-1": "Se han documentado los riesgos residuales tras la implementación de medidas de tratamiento para comunicarlos a los responsables del despliegue.",
    "risk-management-MG14-2": "Se ha documentado todo el proceso de gestión de riesgos, incluyendo metodología, criterios de evaluación y decisiones adoptadas.",
    # ── Data Governance (Article 10) ────────────────────────────────────
    "data-governance-MG01-0": "Se ha identificado toda la información necesaria para el desarrollo y uso del sistema: imágenes faciales, metadatos de empleados y registros de acceso.",
    "data-governance-MG01-1": "La información necesaria se ha documentado en un catálogo de datos que incluye origen, formato, sensibilidad y propósito de cada conjunto.",
    "data-governance-MG02-0": "Se han identificado las fuentes de datos: cámaras de seguridad para imágenes en vivo y sistema de RRHH para imágenes de registro.",
    "data-governance-MG02-1": "Se ha establecido un proceso de recogida de datos que incluye consentimiento explícito del empleado para el registro biométrico.",
    "data-governance-MG03-0": "Se han definido las dimensiones de calidad a evaluar: resolución mínima, iluminación, ángulo facial, nitidez y ausencia de oclusiones.",
    "data-governance-MG04-0": "Se han definido controles de calidad específicos para cada dimensión, incluyendo umbrales mínimos de resolución y claridad de imagen.",
    "data-governance-MG05-0": "Los controles de calidad de imágenes se han implementado mediante validación automática en el pipeline de registro de empleados.",
    "data-governance-MG05-1": "Se han verificado los resultados de los controles: el 98,3% de las imágenes registradas superan los umbrales de calidad establecidos.",
    "data-governance-MG06-0": "Los resultados de los controles de calidad se reportan en informes mensuales al equipo de gobernanza de datos.",
    "data-governance-MG06-1": "Las desviaciones detectadas, como imágenes con baja resolución, se documentan y generan solicitudes de recaptura al empleado.",
    "data-governance-MG07-0": "Se han desarrollado planes de mejora basados en los resultados de calidad, incluyendo mejora de iluminación en puntos de registro.",
    "data-governance-MG07-1": "Se han documentado las medidas de mejora implementadas, como la actualización de cámaras de registro con mejor resolución.",
    "data-governance-MG08-0": "Los datos se han transformado para adaptarlos al sistema: redimensionamiento de imágenes, normalización y alineación facial automática.",
    "data-governance-MG09-0": "Se han agregado datos de imágenes de diferentes fuentes (registro inicial, actualizaciones periódicas) en una base de datos unificada.",
    "data-governance-MG09-1": "El proceso de agregación de datos está documentado, incluyendo reglas de deduplicación y resolución de conflictos entre fuentes.",
    "data-governance-MG10-0": "Se realiza un muestreo estratificado para garantizar representatividad demográfica en los conjuntos de entrenamiento y validación.",
    "data-governance-MG11-0": "Tras la recogida inicial, se identificaron necesidades de datos adicionales para mejorar el rendimiento con diversidad étnica y de edad.",
    "data-governance-MG11-1": "Se ha considerado la reducción de dimensionalidad mediante embeddings faciales de 128 dimensiones para optimizar la comparación.",
    "data-governance-MG12-0": "Se han enriquecido los datos con imágenes en diferentes condiciones de iluminación y ángulos mediante técnicas de augmentación.",
    "data-governance-MG13-0": "Se han asignado etiquetas identificativas a las imágenes, vinculando cada plantilla facial con el identificador único del empleado.",
    "data-governance-MG13-1": "El etiquetado se realiza de forma automática durante el registro, pero se supervisa mediante verificación manual por el equipo de RRHH.",
    "data-governance-MG14-0": "Se ha analizado el sesgo potencial de los datos, evaluando la representatividad por género, edad, etnia y uso de accesorios.",
    "data-governance-MG15-0": "Se identificó un sesgo de subrepresentación de personas con tonos de piel oscuros en el conjunto de entrenamiento inicial.",
    "data-governance-MG15-1": "Se realizó un análisis de impacto y se determinó la necesidad de medidas correctivas para equilibrar la representación demográfica.",
    "data-governance-MG16-0": "Se implementaron medidas de tratamiento: enriquecimiento del conjunto con datos diversos y reentrenamiento del modelo con datos equilibrados.",
    "data-governance-MG17-0": "Se ha generado un informe detallado del proceso de transferencia de datos biométricos entre sistemas durante la migración de infraestructura.",
    "data-governance-MG18-0": "Se ha verificado que ningún usuario ni actor del desarrollo requiere acceso continuo a los datos biométricos tras la baja laboral.",
    "data-governance-MG18-1": "Se ha verificado que el proceso de eliminación no vulnera obligaciones legales, contractuales ni de retención del RGPD.",
    "data-governance-MG18-2": "Se ha verificado que los datos biométricos se eliminan de todas las ubicaciones: base de datos principal, copias de seguridad y cachés.",
    "data-governance-MG18-3": "Se ha evaluado que no es posible restaurar plantillas faciales individuales a partir del modelo entrenado gracias a la irreversibilidad de los embeddings.",
    "data-governance-MG18-4": "Se ha comprobado que los datos biométricos no tienen importancia cultural, social o histórica que impida su eliminación tras la baja.",
    "data-governance-MG18-5": "Se ha generado un informe detallado del proceso de eliminación de datos biométricos, incluyendo confirmación criptográfica de borrado.",
    # ── Accuracy (Article 15) ───────────────────────────────────────────
    "accuracy-MG01-0": "Las métricas de precisión se seleccionaron considerando el propósito del sistema: tasa de acierto, falsos positivos y falsos negativos en control de acceso.",
    "accuracy-MG01-1": "Se ha documentado la correspondencia entre cada métrica seleccionada y el uso previsto del sistema de reconocimiento facial.",
    "accuracy-MG01-2": "Se validó que las métricas elegidas reflejan correctamente el rendimiento esperado en los puntos de acceso reales de las oficinas.",
    "accuracy-MG02-0": "La selección de métricas está motivada por la mitigación de riesgos: la tasa de falsos positivos mitiga el riesgo de acceso no autorizado.",
    "accuracy-MG02-1": "Se han realizado pruebas para estudiar la correlación entre los riesgos detectados y las métricas específicas que los abordan.",
    "accuracy-MG02-2": "Se han priorizado las métricas que controlan los riesgos con mayor impacto: falsos positivos por su impacto en seguridad física.",
    "accuracy-MG03-0": "Se ha documentado el impacto del preprocesamiento de imágenes (normalización, alineación facial) en los resultados de precisión.",
    "accuracy-MG03-1": "Se ha evaluado el impacto de la mejora de calidad de imagen (corrección de iluminación, realce) en la precisión del sistema.",
    "accuracy-MG03-2": "Se ha documentado el impacto de la ingeniería de características, incluyendo la extracción de embeddings faciales de 128 dimensiones.",
    "accuracy-MG04-0": "Se ha considerado y registrado el impacto del sobreajuste, aplicando regularización dropout y early stopping durante el entrenamiento.",
    "accuracy-MG04-1": "Se implementa validación cruzada k-fold con k=5 para prevenir el sobreajuste del modelo de reconocimiento facial.",
    "accuracy-MG04-2": "Se registran indicadores clave (pérdida de entrenamiento vs. validación) para detectar signos de sobreajuste en cada época.",
    "accuracy-MG05-0": "Se han definido criterios para elegir modelos de referencia, comparando FaceNet, ArcFace y modelos propios en cada fase.",
    "accuracy-MG05-1": "La precisión del modelo se compara sistemáticamente con los modelos de referencia en cada actualización del ciclo de vida.",
    "accuracy-MG06-0": "El sistema devuelve una puntuación de confianza (0-100%) junto con cada decisión de acceso concedido o denegado.",
    "accuracy-MG06-1": "El operador de seguridad visualiza el nivel de confianza en el panel, con indicador verde (>95%), amarillo (80-95%) o rojo (<80%).",
    "accuracy-MG06-2": "Se han definido umbrales de confianza: <80% requiere verificación manual obligatoria por el operador de seguridad.",
    "accuracy-MG07-0": "Se han realizado pruebas unitarias, de estrés e integración durante el desarrollo para medir la precisión con volúmenes de 2.000 usuarios.",
    "accuracy-MG07-1": "Los resultados de las pruebas y las acciones derivadas están documentados en el repositorio de validación del modelo.",
    "accuracy-MG07-2": "Se han definido condiciones límite: iluminación mínima <50 lux, oclusiones faciales >30% y ángulos laterales >45°.",
    "accuracy-MG08-0": "La información de métricas de precisión se centraliza en un panel Grafana accesible a todos los actores implicados.",
    "accuracy-MG08-1": "Se ha implementado un sistema de versionado que asocia cada conjunto de métricas con la versión del modelo correspondiente.",
    "accuracy-MG08-2": "Existe un procedimiento formal de comunicación de actualizaciones de métricas mediante correo y notificaciones en el panel.",
    "accuracy-MG09-0": "La función objetivo (triplet loss) se ha seleccionado según el propósito de maximizar la separación entre identidades faciales.",
    "accuracy-MG09-1": "Se han considerado los riesgos del análisis de riesgos y cómo la precisión del sistema influye en ellos, especialmente en accesos indebidos.",
    "accuracy-MG10-0": "El panel de seguridad muestra en tiempo real la precisión del sistema, la tasa de falsos rechazos y alertas de degradación.",
    "accuracy-MG10-1": "El funcionamiento del panel de monitorización de precisión está documentado con capturas de pantalla y guía de usuario.",
    "accuracy-MG10-2": "Los operadores de seguridad han recibido formación práctica para interpretar correctamente las métricas de precisión del panel.",
    "accuracy-MG11-0": "El sistema almacena un historial completo de todas las puntuaciones de confianza reportadas al usuario en cada decisión de acceso.",
    "accuracy-MG11-1": "El historial de precisión puede consultarse por fecha, versión del modelo, sede y contexto de uso.",
    "accuracy-MG11-2": "El historial de precisión se utiliza para ajustar umbrales de confianza y planificar reentrenamientos del modelo.",
    "accuracy-MG12-0": "Se han realizado pruebas de significación estadística (test de McNemar) para justificar la elección de métricas y funciones objetivo.",
    "accuracy-MG12-1": "Los resultados de las pruebas estadísticas están documentados con valores p, intervalos de confianza y tamaños de efecto.",
    "accuracy-MG12-2": "Se han definido criterios mínimos de significación: p < 0,05 y tamaño de efecto d > 0,2 para aceptar diferencias entre modelos.",
    "accuracy-MG13-0": "Se han realizado benchmarks comparando el modelo con los resultados publicados en LFW (Labeled Faces in the Wild) y NIST FRVT.",
    "accuracy-MG13-1": "Se justifica el uso de benchmarks públicos reconocidos (LFW, NIST FRVT) como referencia para validar el rendimiento del modelo.",
    "accuracy-MG13-2": "Para comparaciones internas con datos históricos de acceso manual, se justifica el benchmark interno y su significación estadística.",
    "accuracy-MG13-3": "Se documenta cómo se realizaron las comparaciones con benchmarks y los resultados obtenidos frente a modelos de referencia.",
    "accuracy-MG14-0": "Las instrucciones de uso del sistema incluyen todos los niveles de precisión pertinentes y las métricas asociadas.",
    "accuracy-MG14-1": "Las métricas se presentan en un formato accesible y comprensible para operadores de seguridad sin formación técnica avanzada.",
    # ── Records (Article 12) ────────────────────────────────────────────
    "records-MG01-0": "Se ha desarrollado un proceso para analizar las necesidades de generación de registros del sistema de control de acceso facial.",
    "records-MG01-1": "Se ha evaluado la necesidad de registrar cada evento de acceso, incluyendo resultado, confianza, cámara y marca temporal.",
    "records-MG01-2": "Se han identificado adecuadamente las necesidades: trazabilidad de accesos, auditoría de seguridad y detección de anomalías.",
    "records-MG02-0": "Los objetivos del registro de eventos se han identificado: trazabilidad de accesos, detección de intrusiones y mejora del modelo.",
    "records-MG02-1": "Se ha identificado claramente qué se espera lograr: evidencia forense, cumplimiento normativo y monitorización de rendimiento.",
    "records-MG03-0": "Se ha definido el alcance del registro: cada decisión de acceso, alertas de seguridad y eventos de mantenimiento del sistema.",
    "records-MG03-1": "Se han determinado períodos de retención de 90 días para registros operativos y 5 años para registros de auditoría, conforme al RGPD.",
    "records-MG03-2": "Se han considerado requisitos sectoriales preexistentes aplicables al control de acceso físico en edificios corporativos.",
    "records-MG04-0": "Se han generado los registros necesarios para recopilar la información determinada en el sistema de gestión de riesgos.",
    "records-MG04-1": "Se han considerado los controles del sistema de gestión de riesgos con evidencia asociada para la obtención de registros.",
    "records-MG05-0": "Se generan registros específicos para el sistema de vigilancia poscomercialización, incluyendo métricas de rendimiento diarias.",
    "records-MG05-1": "Las frecuencias de recogida de estos registros se han documentado e implementado: eventos en tiempo real, métricas cada hora.",
    "records-MG06-0": "Se generan registros para la supervisión humana, incluyendo las decisiones revisadas manualmente por el operador de seguridad.",
    "records-MG06-1": "Se ha documentado la necesidad de estos registros y cómo interpretar sus resultados para la supervisión humana del sistema.",
    "records-MG07-0": "Se ha implementado un proceso de captura de registros que garantiza la recogida según los criterios de la fase de diseño.",
    "records-MG07-1": "Se han realizado pruebas de validación de los procedimientos de captura de registros en un entorno de preproducción.",
    "records-MG07-2": "Se han realizado pruebas de estrés del sistema de captura de registros simulando 10.000 accesos simultáneos sin pérdida de datos.",
    "records-MG08-0": "Los registros se almacenan en una base de datos PostgreSQL con cifrado en reposo y replicación en un segundo centro de datos de la UE.",
    "records-MG08-1": "Se han establecido períodos de supervisión trimestral y revisión anual de los soportes de almacenamiento de registros.",
    "records-MG09-0": "Se aplican medidas de ciberseguridad: cifrado AES-256, acceso por rol y registros inmutables con hashing para garantizar la integridad.",
    "records-MG09-1": "Se han establecido períodos de revisión semestral de las medidas de ciberseguridad y controles de acceso a los registros.",
    "records-MG10-0": "Se imparte formación trimestral al personal implicado en la gestión de registros sobre procedimientos y herramientas de consulta.",
    "records-MG10-1": "Las necesidades de formación en gestión de registros se contemplan en el programa de alfabetización en IA del Artículo 4.",
    "records-MG11-0": "Se ha analizado el impacto del RGPD y la normativa de protección de datos en la generación de registros biométricos.",
    "records-MG11-1": "Específicamente, se ha evaluado que los registros no almacenan plantillas faciales, solo identificadores anonimizados y resultados de decisión.",
    "records-MG12-0": "Se han establecido períodos de supervisión trimestral de soportes de almacenamiento, ciberseguridad y controles de acceso.",
    "records-MG12-1": "Se han establecido períodos de revisión anual completa de soportes, medidas de ciberseguridad y controles de acceso a registros.",
    "records-MG13-0": "Se ha establecido un proceso de monitorización y mejora continua del sistema de gestión de registros del sistema biométrico.",
    "records-MG13-1": "Se monitorizan errores de captura, se evalúan datos registrados y se implementan mejoras de forma continua en el sistema.",
    "records-MG14-0": "Se ha definido un proceso que garantiza la documentación técnica adecuada del sistema de gestión de registros implementado.",
    "records-MG14-1": "Los registros se contemplan tanto en su documentación específica como en documentos de riesgos, supervisión y vigilancia poscomercialización.",
    "records-MG15-0": "El sistema cumple con las medidas de precisión, robustez y ciberseguridad orientadas a proporcionar transparencia sobre su funcionamiento.",
    "records-MG16-0": "El sistema cumple con las medidas de conservación de registros orientadas a proporcionar transparencia sobre su funcionamiento.",
    # ── Robustness (Article 15) ─────────────────────────────────────────
    "robustness-MG01-0": "El personal de desarrollo y operaciones ha recibido formación sobre robustez de sistemas biométricos, incluyendo detección de ataques de presentación.",
    "robustness-MG02-0": "Se han establecido propiedades y métricas de robustez: tiempo de respuesta <2s, disponibilidad 99,9% y tolerancia a variaciones de iluminación.",
    "robustness-MG03-0": "Se han identificado características medibles de robustez: latencia, throughput, tasa de error bajo condiciones adversas y separabilidad de métricas.",
    "robustness-MG04-0": "Los entornos de desarrollo, integración, preproducción y producción tienen características equivalentes según los objetivos de robustez.",
    "robustness-MG05-0": "Se ha verificado y validado el rendimiento en hardware idéntico al de producción: GPUs de inferencia y cámaras IR del mismo modelo.",
    "robustness-MG06-0": "Se han definido métricas de rendimiento en el hardware establecido: inferencias por segundo, latencia p95 y eficiencia energética por decisión.",
    "robustness-MG07-0": "Existe un plan de experimentos para demostrar la robustez mediante pruebas estadísticas, empíricas y prácticas en condiciones reales.",
    "robustness-MG08-0": "Se dispone de evidencia de los experimentos realizados, su análisis e interpretación, y su impacto en los parámetros de robustez.",
    "robustness-MG09-0": "Se han definido procedimientos de monitorización de robustez, incluyendo paneles Grafana con métricas agregadas e históricas.",
    "robustness-MG10-0": "Existen alertas automáticas que se activan cuando la latencia supera 3 segundos o la disponibilidad cae por debajo del 99,5%.",
    "robustness-MG11-0": "Se ha establecido un comité técnico mensual para evaluar proactivamente inconsistencias o posibles fallos en la robustez del sistema.",
    "robustness-MG12-0": "Existen mecanismos automáticos de recuperación: failover a servidor de respaldo y modo de acceso alternativo con tarjeta en caso de fallo.",
    "robustness-MG13-0": "Se ha implementado redundancia geográfica entre dos centros de datos de la UE, gestión de versiones con rollback y escalado automático.",
    "robustness-MG14-0": "El sistema no realiza aprendizaje continuo en producción; los reentrenamientos son controlados y validados antes del despliegue.",
    "robustness-MG15-0": "Se han establecido planes de monitorización y control con medidas de acción para degradación del modelo por deriva de datos.",
    "robustness-MG16-0": "Las interacciones, interoperabilidad y retroalimentación recibida durante el ciclo de vida se registran formalmente para mejorar la robustez.",
    # ── Oversight (Article 14) ──────────────────────────────────────────
    "oversight-MG01-0": "El sistema de reconocimiento facial dispone de un sistema de gestión de riesgos conforme al Artículo 9 del Reglamento.",
    "oversight-MG01-1": "El sistema dispone de un modelo de gobernanza de datos conforme al Artículo 10 para la gestión de imágenes biométricas.",
    "oversight-MG01-2": "El sistema dispone de documentación técnica conforme al Artículo 11, cubriendo todos los aspectos del sistema biométrico.",
    "oversight-MG01-3": "El sistema dispone de gestión de registros conforme al Artículo 12 para eventos de acceso y decisiones del modelo.",
    "oversight-MG01-4": "El sistema dispone de mecanismos de transparencia conforme al Artículo 13 para informar a empleados y operadores.",
    "oversight-MG01-5": "El sistema dispone de mecanismos de precisión conforme al Artículo 15 con métricas documentadas y monitorizadas.",
    "oversight-MG01-6": "El sistema dispone de mecanismos de robustez conforme al Artículo 15 con redundancia y monitorización continua.",
    "oversight-MG01-7": "El sistema dispone de mecanismos de ciberseguridad conforme al Artículo 15 con cifrado, aislamiento de red y controles de acceso.",
    "oversight-MG02-0": "El sistema dispone de una interfaz de gestión de riesgos donde el operador puede consultar y actualizar la evaluación de riesgos.",
    "oversight-MG02-1": "El sistema dispone de una interfaz para gestionar el modelo de gobernanza de datos biométricos y sus controles de calidad.",
    "oversight-MG02-2": "El sistema dispone de una interfaz para gestionar la documentación técnica, con acceso al repositorio y control de versiones.",
    "oversight-MG02-3": "El sistema dispone de una interfaz para consultar los registros de acceso, filtrar por fecha, sede y resultado de decisión.",
    "oversight-MG02-4": "El sistema dispone de una interfaz para gestionar la transparencia, incluyendo información sobre el funcionamiento del sistema.",
    "oversight-MG02-5": "El sistema dispone de una interfaz para gestionar la precisión, mostrando métricas en tiempo real y tendencias históricas.",
    "oversight-MG02-6": "El sistema dispone de una interfaz para gestionar la robustez, con alertas de rendimiento y estado de los componentes.",
    "oversight-MG02-7": "El sistema dispone de una interfaz para gestionar la ciberseguridad, incluyendo alertas de intrusiones y estado de certificados.",
    "oversight-MG03-0": "Se ha establecido un modelo de gobernanza con estructura organizativa, procedimientos y formación para operadores de seguridad.",
    "oversight-MG03-1": "El modelo de gobernanza incluye validación de la identificación por al menos dos personas con competencia y autoridad acreditada.",
    "oversight-MG04-0": "El sistema incorpora verificaciones aleatorias obligatorias para evitar el sesgo de automatización entre los operadores de seguridad.",
    "oversight-MG05-0": "Se ha contemplado el nivel de autonomía del sistema: decisión automática con confianza >95%, intervención humana obligatoria por debajo.",
    "oversight-MG05-1": "El operador dispone de un botón de parada de emergencia en el panel que bloquea todos los tornos e impone acceso manual.",
    "oversight-MG06-0": "El sistema dispone de un plan de gestión de riesgos actualizado y accesible desde la interfaz de supervisión.",
    "oversight-MG07-0": "El sistema dispone de mecanismos de transparencia que permiten al operador comprender y supervisar correctamente su funcionamiento.",
    "oversight-MG08-0": "El sistema cumple con las medidas de conservación de registros orientadas a proporcionar transparencia sobre su funcionamiento.",
    # ── Transparency (Article 13) ───────────────────────────────────────
    "transparency-MG01-0": "El sistema dispone de un portal web para la gestión en línea de solicitudes e incidencias relacionadas con el reconocimiento facial.",
    "transparency-MG01-1": "El modelo de gobernanza establece un punto de contacto claro del proveedor disponible para los responsables del despliegue.",
    "transparency-MG02-0": "El sistema cubre los requisitos de transparencia aplicables a sistemas de identificación biométrica de alto riesgo.",
    "transparency-MG02-1": "Se proporciona información detallada sobre el alcance funcional, incluyendo riesgos de usos no previstos como vigilancia masiva.",
    "transparency-MG03-0": "Se proporciona información sobre circunstancias previsibles de uso indebido, como intentos de vigilancia no autorizada.",
    "transparency-MG03-1": "El sistema va acompañado de un plan de riesgos para usos indebidos, incluyendo límites técnicos contra la vigilancia masiva.",
    "transparency-MG03-2": "Existe un procedimiento de supervisión para verificar que no se producen usos indebidos del sistema durante la operación.",
    "transparency-MG04-0": "El sistema identifica las fuentes de datos utilizadas: imágenes de registro de RRHH y capturas en tiempo real de cámaras de acceso.",
    "transparency-MG04-1": "El sistema dispone de herramientas de análisis exploratorio de datos que permiten inspeccionar la distribución del conjunto de entrenamiento.",
    "transparency-MG05-0": "El sistema proporciona mecanismos técnicos de explicabilidad global mediante análisis de importancia de características faciales.",
    "transparency-MG05-1": "Se proporcionan mecanismos de explicabilidad por subgrupos para verificar la homogeneidad del rendimiento entre grupos demográficos.",
    "transparency-MG05-2": "Se proporcionan mapas de atención (Grad-CAM) para explicar qué regiones faciales influyeron en cada decisión individual.",
    "transparency-MG06-0": "Se proporcionan explicaciones del razonamiento global del sistema en lenguaje comprensible para todos los actores del ciclo de vida.",
    "transparency-MG06-1": "Se proporcionan explicaciones de las acciones sobre subconjuntos de información (por grupo demográfico) en lenguaje comprensible.",
    "transparency-MG06-2": "Se proporcionan explicaciones de cada decisión individual de acceso en lenguaje comprensible para el operador de seguridad.",
    "transparency-MG07-0": "La complejidad técnica del modelo CNN no bloquea las necesidades de transparencia gracias a los mecanismos de explicabilidad implementados.",
    "transparency-MG07-1": "Para el modelo de caja negra, el proveedor suministra herramientas de explicabilidad (Grad-CAM, SHAP) que habilitan la transparencia.",
    "transparency-MG08-0": "Se proporcionan métricas de datos, modelo, calidad de resultados y rendimiento, con valores mínimos aceptables definidos.",
    "transparency-MG08-1": "El sistema cuenta con un pipeline MLOps de integración continua que identifica cómo los cambios de métricas afectan a cada versión.",
    "transparency-MG09-0": "El sistema implementa filtros de salida que impiden la exposición de plantillas biométricas o información confidencial del modelo.",
    "transparency-MG10-0": "Se proporcionan herramientas para identificar y analizar correlaciones no deseadas que puedan afectar a la transparencia o precisión.",
    "transparency-MG11-0": "El sistema proporciona mecanismos técnicos para obtener contrafactuales que facilitan la comprensión de las decisiones de acceso.",
    "transparency-MG12-0": "El sistema dispone de una wiki interna con información completa sobre su funcionamiento, accesible a todas las personas con responsabilidad.",
    "transparency-MG13-0": "El sistema dispone de un plan de gestión de riesgos actualizado y documentado conforme al Artículo 9.",
    "transparency-MG14-0": "El sistema cumple con las medidas de supervisión humana establecidas conforme al Artículo 14 del Reglamento.",
    "transparency-MG15-0": "El sistema cumple con las medidas de precisión, robustez y ciberseguridad orientadas a proporcionar transparencia.",
    "transparency-MG16-0": "El sistema cumple con las medidas de conservación de registros orientadas a proporcionar transparencia sobre su funcionamiento.",
    # ── Surveillance (Article 72) ───────────────────────────────────────
    "surveillance-MG01-0": "Se han identificado y documentado todos los riesgos relevantes del entorno de producción: fallos de cámaras, degradación del modelo y ataques.",
    "surveillance-MG01-1": "El diseño del sistema de vigilancia integra medidas específicas para cada riesgo identificado en el entorno operativo.",
    "surveillance-MG02-0": "Se han definido indicadores clave que cubren sistema de IA, infraestructura, ciberseguridad y experiencia del usuario de forma integral.",
    "surveillance-MG02-1": "La selección de indicadores se basa en criterios de relevancia y criticidad del entorno, con justificación documentada.",
    "surveillance-MG02-2": "La eficacia y pertinencia de los indicadores se ha validado en pruebas piloto en una sede antes del despliegue completo.",
    "surveillance-MG03-0": "Se han establecido rangos de valores aceptables para cada indicador basados en análisis históricos y escenarios esperados.",
    "surveillance-MG03-1": "La determinación de estos rangos está justificada y alineada con las condiciones operativas reales de las oficinas.",
    "surveillance-MG03-2": "Existe un mecanismo de actualización trimestral de los rangos basado en nuevos datos recopilados y evolución del entorno.",
    "surveillance-MG04-0": "El sistema incorpora un mecanismo de alertas en tiempo real que monitoriza continuamente los indicadores clave de rendimiento.",
    "surveillance-MG04-1": "Se han configurado umbrales críticos que, al superarse, activan alertas inmediatas al equipo de seguridad y operaciones.",
    "surveillance-MG04-2": "Se han realizado pruebas en entornos simulados y reales para garantizar la fiabilidad y rapidez de activación de alertas.",
    "surveillance-MG05-0": "Se ha planificado y documentado un proceso de despliegue controlado del sistema de vigilancia en el entorno de producción.",
    "surveillance-MG05-1": "El sistema de vigilancia se ha desplegado con éxito en producción en todas las sedes operativas de la UE.",
    "surveillance-MG06-0": "Se han ejecutado pruebas en el entorno de producción para validar la operatividad y robustez del sistema de vigilancia.",
    "surveillance-MG07-0": "Existe una política formal que contempla tanto la monitorización continua como las revisiones periódicas del sistema de vigilancia.",
    "surveillance-MG07-1": "Los roles y responsabilidades de vigilancia están claramente definidos y respaldados por la dirección de la organización.",
    "surveillance-MG07-2": "La política de vigilancia se revisa y actualiza semestralmente para adaptarse a cambios del entorno o nuevos riesgos.",
    "surveillance-MG08-0": "Se han identificado y documentado escenarios anómalos que podrían comprometer el rendimiento: pérdida de conectividad, fallo de GPU y saturación.",
    "surveillance-MG08-1": "Existen planes de contingencia y medidas específicas para gestionar cada escenario anómalo identificado.",
    "surveillance-MG09-0": "Se ha designado un responsable de vigilancia poscomercialización con autoridad necesaria para coordinar las actividades.",
    "surveillance-MG09-1": "El compromiso de la alta dirección se refleja en la asignación de recursos y la comunicación interna sobre vigilancia.",
    "surveillance-MG09-2": "Existe documentación del plan de vigilancia que evidencia el liderazgo y la coordinación de las actividades de monitorización.",
    "surveillance-MG10-0": "Se ha formado un equipo específico de respuesta a alertas con formación en sistemas biométricos y gestión de incidentes.",
    "surveillance-MG10-1": "Los roles y responsabilidades del equipo de respuesta están claramente definidos y comunicados a toda la organización.",
    "surveillance-MG11-0": "Existe un protocolo formal y documentado de respuesta que detalla las acciones a seguir ante la detección de un incidente.",
    "surveillance-MG11-1": "Se ha generado una plantilla de informe de incidentes que incluye causa raíz, impacto, acciones correctivas y seguimiento.",
    "surveillance-MG12-0": "Se han identificado las necesidades de formación de todo el personal implicado en la vigilancia poscomercialización.",
    "surveillance-MG12-1": "Se realizan ejercicios de formación y simulaciones de respuesta trimestrales para evaluar la eficacia y coordinación del equipo.",
    "surveillance-MG13-0": "Se han definido y documentado períodos de revisión trimestrales para evaluar el funcionamiento y eficacia del sistema de vigilancia.",
    # ── UNDP Zero Questions ─────────────────────────────────────────────
    "undp-zero-question-ZQ-01-0": "Se evaluó la necesidad de IA frente a alternativas como tarjetas RFID; se justificó por mayor seguridad ante suplantación de tarjetas.",
    "undp-zero-question-ZQ-02-0": "Se documentó la justificación: el reconocimiento facial elimina riesgos de pérdida, robo y préstamo de tarjetas de acceso.",
    "undp-zero-question-ZQ-03-0": "Se realizó un análisis DAFO comparando reconocimiento facial con tarjetas RFID, códigos PIN y acceso con huella dactilar.",
    "undp-zero-question-ZQ-04-0": "Se confirmó que el sistema no persigue un objetivo incompatible con derechos fundamentales; se limita a control de acceso autorizado.",
    # ── UNDP Organisational Readiness ───────────────────────────────────
    "undp-org-readiness-OR-01-0": "La organización dispone de una política documentada de derechos humanos que cubre el diseño, desarrollo y despliegue de sistemas de IA.",
    "undp-org-readiness-OR-02-0": "La dirección apoya activamente y asigna recursos para la debida diligencia en derechos humanos en iniciativas de IA biométrica.",
    "undp-org-readiness-OR-03-0": "Existen canales confidenciales para que los empleados reporten posibles problemas de derechos humanos relacionados con el sistema.",
    "undp-org-readiness-OR-04-0": "La organización revisa y actualiza sus políticas anualmente para abordar cuestiones emergentes de IA y derechos humanos.",
    "undp-org-readiness-OR-06-0": "Se consulta a los empleados afectados (usuarios del sistema de acceso) durante el ciclo de vida del proyecto biométrico.",
    "undp-org-readiness-OR-07-0": "La organización asigna recursos suficientes para formación, evaluaciones de riesgos y participación de las partes interesadas.",
    "undp-org-readiness-OR-08-0": "Se prioriza la transparencia y comunicación pública sobre el uso del sistema de reconocimiento facial en las oficinas.",
    "undp-org-readiness-OR-09-0": "El equipo directivo tiene comprensión integral de las implicaciones del reconocimiento facial en derechos humanos y privacidad.",
    "undp-org-readiness-OR-10-0": "Los empleados reciben formación anual sobre derechos humanos y consideraciones éticas del uso de IA biométrica.",
    "undp-org-readiness-OR-11-0": "Existe un equipo de ética de IA designado responsable de monitorizar y abordar problemas de derechos humanos en el proyecto.",
    "undp-org-readiness-OR-13-0": "Los empleados están protegidos contra represalias cuando plantean preocupaciones sobre el impacto del sistema en derechos humanos.",
    "undp-org-readiness-OR-14-0": "Existe un proceso formal para incorporar la retroalimentación de empleados y partes interesadas en las prácticas del sistema.",
    "undp-org-readiness-OR-17-0": "La organización participa en grupos sectoriales y foros sobre derechos humanos, ética y biometría en la UE.",
    "undp-org-readiness-OR-18-0": "La organización evalúa periódicamente las carencias de competencias en derechos humanos e IA entre su personal técnico.",
    "undp-org-readiness-OR-19-0": "Existe un proceso sistemático de evaluación de impacto en derechos humanos para el proyecto de reconocimiento facial.",
    "undp-org-readiness-OR-20-0": "Existen procedimientos para evaluar el impacto de componentes de IA de terceros (modelos preentrenados, bibliotecas de visión).",
    "undp-org-readiness-OR-21-0": "Existe un proceso sistemático de identificación de riesgos que incluye pruebas de fiabilidad, precisión y resiliencia del modelo.",
    "undp-org-readiness-OR-22-0": "Los empleados afectados (usuarios del control de acceso) participan en el proceso de despliegue mediante encuestas y sesiones informativas.",
    "undp-org-readiness-OR-23-0": "Todos los proyectos de IA se someten a una evaluación de impacto en derechos humanos y protección de datos antes del despliegue.",
    "undp-org-readiness-OR-24-0": "Se han establecido protocolos de seguridad de datos y privacidad para todos los procesos relacionados con la biometría facial.",
    "undp-org-readiness-OR-25-0": "Los procesos se actualizan periódicamente para incorporar nuevas regulaciones como el Reglamento de IA y actualizaciones del RGPD.",
    "undp-org-readiness-OR-26-0": "Se ha establecido un proceso de supervisión para monitorizar el rendimiento y el cumplimiento de estándares de derechos humanos.",
    "undp-org-readiness-OR-27-0": "La organización puede mitigar y minimizar los efectos negativos de fallos del sistema, incluyendo acceso alternativo inmediato.",
    "undp-org-readiness-OR-28-0": "Existe un mecanismo de reparación para personas perjudicadas por errores del sistema, incluyendo procedimiento de reclamación documentado.",
    # ── UNDP Planning ───────────────────────────────────────────────────
    "undp-planning-PS-02-0": "Se han documentado las características técnicas: modelo CNN de reconocimiento facial, arquitectura ResNet-50 con embeddings de 128 dimensiones.",
    "undp-planning-PS-03-0": "Se han identificado todos los países de la UE donde se desplegará el sistema, con análisis de normativa local aplicable.",
    "undp-planning-PS-04-0": "Se han identificado todos los tipos de datos procesados: datos biométricos faciales (categoría especial RGPD), metadatos de acceso y registros.",
    "undp-planning-PS-05-0": "Se han mapeado todos los flujos de datos: captura por cámara, procesamiento en servidor local, almacenamiento cifrado y eliminación tras baja.",
    "undp-planning-PS-06-0": "Se han identificado todas las personas potencialmente afectadas: empleados registrados, visitantes y personal de seguridad.",
    "undp-planning-PS-07-0": "Se ha evaluado que los grupos afectados no incluyen personas especialmente vulnerables; el sistema se limita a empleados adultos.",
    "undp-planning-PS-08-0": "Se han identificado todos los responsables: proveedor del modelo, equipo de TI, departamento de seguridad y dirección de instalaciones.",
    "undp-planning-PS-10-0": "Se han documentado las políticas y procedimientos existentes para evaluar impactos en derechos humanos, incluyendo consulta a empleados.",
    "undp-planning-PS-11-0": "Se ha documentado la Evaluación de Impacto en la Protección de Datos (EIPD) realizada conforme al artículo 35 del RGPD.",
    "undp-planning-PS-12-0": "Se han identificado todos los grupos potencialmente afectados, incluyendo empleados con discapacidades faciales o que usen velo.",
    "undp-planning-PS-13-0": "Se han identificado las partes interesadas relevantes: comité de empresa, DPO, autoridad de protección de datos y expertos en biometría.",
    "undp-planning-PS-14-0": "Se han identificado responsables adicionales: autoridades nacionales de protección de datos y agencias de supervisión del mercado.",
    "undp-planning-PS-15-0": "Se ha evaluado la participación de socios comerciales: el proveedor del modelo de IA y el fabricante de cámaras han sido consultados.",
    "undp-planning-PS-16-0": "Se ha realizado una evaluación de la cadena de suministro del proveedor del modelo facial para identificar impactos potenciales.",
    "undp-planning-PS-17-0": "Se han promovido estándares de derechos humanos entre los proveedores, requiriendo certificaciones de equidad en el entrenamiento.",
    "undp-planning-PS-18-0": "El proveedor y los desarrolladores comunican públicamente los impactos potenciales del sistema de reconocimiento facial.",
    "undp-planning-PS-19-0": "Se proporciona formación sobre estándares de derechos humanos al personal de dirección y aprovisionamiento involucrado.",
    # ── UNDP Rights Mapping ─────────────────────────────────────────────
    "undp-rights-mapping-HRM-01-0": "Se han identificado todos los derechos humanos potencialmente afectados: privacidad, no discriminación, libertad de movimiento y dignidad.",
    "undp-rights-mapping-HRM-06-0": "Se ha evaluado el impacto en la libertad frente a tratos inhumanos: el sistema no se usa para fines degradantes ni vigilancia invasiva.",
    "undp-rights-mapping-HRM-09-0": "Se ha evaluado el impacto en la libertad de pensamiento y conciencia: el sistema no infiere estados mentales ni creencias religiosas.",
    "undp-rights-mapping-HRM-13-0": "Se ha evaluado el impacto en la libertad de asociación: el sistema no rastrea con quién acceden los empleados al edificio.",
    "undp-rights-mapping-HRM-15-0": "Se ha evaluado el impacto en el derecho a un nivel de vida adecuado: la denegación de acceso no afecta condiciones de vida básicas.",
    "undp-rights-mapping-HRM-18-0": "Se ha evaluado el impacto en el derecho a participar en la vida cultural: el sistema no impide el acceso a actividades culturales.",
    "undp-rights-mapping-HRM-21-0": "Se ha evaluado el impacto en los derechos de minorías: se verificó que el modelo no discrimina por etnia, religión o lengua.",
    "undp-rights-mapping-HRM-24-0": "Se ha evaluado el impacto en el derecho al reconocimiento de la personalidad jurídica: el sistema no afecta este derecho.",
    "undp-rights-mapping-HRM-25-0": "Se ha evaluado el impacto en la igualdad ante la ley: se verificó que el rendimiento es equitativo entre todos los grupos demográficos.",
    "undp-rights-mapping-HRM-33-0": "Se ha evaluado el impacto en el derecho a participar en asuntos públicos: el sistema de acceso no restringe la participación cívica.",
    "undp-rights-mapping-HRM-34-0": "Se han identificado los instrumentos legales internacionales y regionales aplicables: CEDH, Carta de Derechos Fundamentales de la UE y RGPD.",
    "undp-rights-mapping-HRM-36-0": "Se ha identificado la jurisprudencia relevante del TJUE sobre biometría, protección de datos y derechos fundamentales en la UE.",
    # ── UNDP Data Diligence ─────────────────────────────────────────────
    "undp-data-diligence-DD-01-0": "El origen de los datos de entrenamiento está documentado: imágenes capturadas durante el registro voluntario de empleados.",
    "undp-data-diligence-DD-03-0": "Se han tomado medidas para garantizar que los datos representan la diversidad de la población empleada por género, edad, etnia y discapacidad.",
    "undp-data-diligence-DD-04-0": "Se han identificado y documentado las limitaciones conocidas: menor rendimiento en condiciones de baja iluminación y con oclusiones faciales.",
    "undp-data-diligence-DD-05-0": "Los datos biométricos se manejan y protegen adecuadamente durante todo el ciclo de vida conforme al RGPD y normativa de categoría especial.",
    "undp-data-diligence-DD-06-0": "El proceso de etiquetado de imágenes está documentado, incluyendo la vinculación automática con el ID de empleado y verificación manual.",
    "undp-data-diligence-DD-07-0": "El objetivo específico del entrenamiento está documentado: maximizar la precisión de identificación minimizando el sesgo demográfico.",
    "undp-data-diligence-DD-08-0": "Se utilizaron criterios de equidad durante el entrenamiento: paridad demográfica, igualdad de oportunidades y tasas de error equilibradas.",
    "undp-data-diligence-DD-09-0": "Se documentan las limitaciones conocidas del modelo: sensibilidad a cambios de apariencia, iluminación extrema y ángulos >45°.",
    "undp-data-diligence-DD-10-0": "Se documenta el tipo de modelo (CNN con arquitectura ResNet-50) y la justificación de su selección frente a alternativas evaluadas.",
    "undp-data-diligence-DD-12-0": "Los resultados de rendimiento están desglosados por subgrupos de género, edad y etnia, mostrando diferencias <2% entre grupos.",
    "undp-data-diligence-DD-14-0": "Se dispone de funcionalidades de explicabilidad (Grad-CAM y SHAP) para explicar decisiones específicas del sistema.",
    "undp-data-diligence-DD-17-0": "Existe un proceso formal para gestionar quejas y reclamaciones de empleados que consideren que el sistema les afecta negativamente.",
    "undp-data-diligence-DD-18-0": "Se han realizado pruebas con casos límite: maquillaje extremo, gafas de sol, mascarillas, cicatrices y variaciones de peso significativas.",
    "undp-data-diligence-DD-19-0": "Se han realizado pruebas de sesgo con perfiles demográficos idénticos variando género, edad y etnia para verificar equidad.",
    "undp-data-diligence-DD-20-0": "Se han realizado pruebas de funcionalidad verificando que el sistema identifica correctamente a empleados registrados de forma fiable.",
    "undp-data-diligence-DD-21-0": "Se ha verificado la accesibilidad: interfaces alternativas para personas con discapacidad visual y acceso manual de respaldo.",
    "undp-data-diligence-DD-22-0": "Se ha revisado que las salidas del sistema no contienen errores, decisiones sesgadas ni contenido perjudicial para los empleados.",
    # ── UNDP Risk Analysis ──────────────────────────────────────────────
    "undp-risk-analysis-RA-01-0": "Se ha evaluado la probabilidad de resultados adversos para cada derecho afectado: privacidad (Alta), no discriminación (Media), dignidad (Baja).",
    "undp-risk-analysis-RA-02-0": "Se ha evaluado la exposición: el 100% de los empleados (~2.000 por sede) están expuestos al sistema diariamente, exposición Muy Alta.",
    "undp-risk-analysis-RA-03-0": "Se ha calculado la probabilidad global mediante la matriz Probabilidad x Exposición para cada derecho afectado.",
    "undp-risk-analysis-RA-04-0": "Se ha evaluado la gravedad del perjuicio considerando intensidad, consecuencias e impacto en grupos específicos para cada derecho.",
    "undp-risk-analysis-RA-05-0": "Se ha evaluado el esfuerzo para superar los efectos adversos: los accesos denegados erróneamente son reversibles mediante intervención manual.",
    "undp-risk-analysis-RA-07-0": "Se ha calculado el índice de riesgo para cada derecho afectado mediante la matriz Probabilidad x Gravedad documentada.",
    "undp-risk-analysis-RA-08-0": "Se ha creado un gráfico radial que muestra el impacto en todos los derechos afectados para facilitar la visualización.",
    "undp-risk-analysis-RA-09-0": "Cada derecho se ha evaluado de forma independiente, sin crear un índice acumulativo que combine impactos entre derechos distintos.",
    "undp-risk-analysis-RA-10-0": "Se han evaluado factores de exclusión de riesgo: las limitaciones legales del RGPD justifican medidas de protección adicionales.",
    "undp-risk-analysis-RA-11-0": "Se ha aplicado un test de ponderación donde existen derechos en conflicto (seguridad física vs. privacidad biométrica).",
    "undp-risk-analysis-RA-12-0": "Se han analizado los beneficios potenciales: mejora de la seguridad física y protección del derecho a la integridad personal.",
    # ── UNDP Risk Management ────────────────────────────────────────────
    "undp-risk-management-RMG-01-0": "Se han identificado medidas de mitigación para cada riesgo Medio, Alto o Muy Alto: cifrado reforzado, auditorías de sesgo y acceso alternativo.",
    "undp-risk-management-RMG-02-0": "Las medidas están contextualizadas al sistema biométrico facial, su despliegue en oficinas de la UE y la población de 2.000 empleados.",
    "undp-risk-management-RMG-06-0": "Tras implementar medidas de mitigación, se ha reevaluado el riesgo residual: privacidad reducida de Alto a Medio, discriminación de Medio a Bajo.",
    "undp-risk-management-RMG-11-0": "No se detectaron riesgos residuales Altos o Muy Altos tras las medidas de mitigación implementadas.",
    "undp-risk-management-RMG-12-0": "Se mantiene un registro completo de todas las decisiones de evaluación de riesgos, justificaciones de puntuación y opciones de la matriz.",
    "undp-risk-management-RMG-15-0": "Las medidas de mitigación y su eficacia esperada están documentadas en el informe de evaluación de impacto en derechos humanos.",
    # ── UNDP Monitoring ─────────────────────────────────────────────────
    "undp-monitoring-MI-01-0": "Se ha establecido un plan de monitorización del rendimiento posdesplegue que incluye métricas de precisión, sesgo y disponibilidad.",
    "undp-monitoring-MI-02-0": "Se ha establecido un calendario de reevaluación semestral con enfoque iterativo circular para la evaluación de impacto.",
    "undp-monitoring-MI-04-0": "Se han establecido canales de retroalimentación para que los empleados reporten problemas de acceso o discriminación percibida.",
    "undp-monitoring-MI-05-0": "Existe un mecanismo de reparación operativo para empleados perjudicados, incluyendo acceso manual inmediato y revisión de su caso.",
    "undp-monitoring-MI-06-0": "Se han definido disparadores para reevaluación completa: actualización del modelo, nueva sede, cambio normativo o incidentes reportados.",
    "undp-monitoring-MI-07-0": "Existe un proceso para incorporar nuevas regulaciones y estándares a medida que se publican, incluyendo actualizaciones del Reglamento de IA.",
    "undp-monitoring-MI-08-0": "Los resultados de la monitorización retroalimentan el ciclo de evaluación de riesgos y las medidas de mitigación activas.",
    # ── UNDP Framework Alignment ────────────────────────────────────────
    "undp-framework-alignment-FA-01-0": "Se tiene conocimiento de las obligaciones estatales en las jurisdicciones de despliegue de la UE respecto a biometría y vigilancia.",
    "undp-framework-alignment-FA-02-0": "La organización ha realizado la debida diligencia en derechos humanos a lo largo de todo el ciclo de vida del sistema biométrico.",
    "undp-framework-alignment-FA-03-0": "Existen mecanismos efectivos de reclamación para empleados afectados, incluyendo procedimiento formal y plazo de respuesta de 15 días.",
    "undp-framework-alignment-FA-04-0": "El sistema beneficia a la sociedad mejorando la seguridad de las instalaciones sin exacerbar desigualdades entre empleados.",
    "undp-framework-alignment-FA-05-0": "Se ha completado una evaluación de discriminación potencial y resultados inequitativos desglosada por grupos demográficos.",
    "undp-framework-alignment-FA-06-0": "Se documenta cómo funciona el sistema, sus limitaciones y cómo toma decisiones de acceso para todos los actores implicados.",
    "undp-framework-alignment-FA-07-0": "Se han evaluado los modos de fallo, vulnerabilidades de seguridad y fiabilidad del sistema de reconocimiento facial.",
    "undp-framework-alignment-FA-08-0": "Se han establecido responsabilidades claras y mecanismos de supervisión para el desarrollo, despliegue y operación del sistema.",
    "undp-framework-alignment-FA-09-0": "Se ha determinado la clasificación de riesgo del sistema de IA como alto riesgo por el tratamiento de datos biométricos.",
    "undp-framework-alignment-FA-10-0": "Se ha realizado una Evaluación de Impacto en Derechos Fundamentales (EIDF) conforme al Artículo 27 del Reglamento de IA.",
    "undp-framework-alignment-FA-11-0": "Se aplican medidas de gobernanza de datos que incluyen minimización, cifrado y controles de acceso basados en roles.",
    "undp-framework-alignment-FA-12-0": "Se han cumplido las obligaciones de transparencia: los empleados son informados de que se utiliza reconocimiento facial para el acceso.",
    "undp-framework-alignment-FA-13-0": "Los requisitos de supervisión humana están documentados: los operadores pueden anular decisiones y activar el modo de acceso manual.",
    "undp-framework-alignment-FA-14-0": "Se mantiene documentación técnica actualizada conforme al Anexo IV del Reglamento de IA, revisada trimestralmente.",
    "undp-framework-alignment-FA-15-0": "El sistema está registrado en la base de datos de la UE para sistemas de IA de alto riesgo conforme al Artículo 71.",
    "undp-framework-alignment-FA-16-0": "Se ha evaluado el impacto del sistema en derechos humanos, democracia y estado de derecho conforme a los marcos aplicables.",
    "undp-framework-alignment-FA-17-0": "El sistema cumple con el énfasis del Convenio del Consejo de Europa en derechos humanos, principios democráticos y estado de derecho.",
    # ── UNDP — Missing entries ────────────────────────────────────────────
    "undp-org-readiness-OR-05-0": "Se facilita la colaboración interdepartamental entre seguridad, TI, legal y RRHH para abordar cuestiones de derechos humanos en el sistema de IA.",
    "undp-org-readiness-OR-12-0": "La organización colabora con expertos externos en derechos humanos y ética de la IA mediante un panel consultivo semestral.",
    "undp-org-readiness-OR-15-0": "Se cuenta con asesoramiento jurídico especializado en derechos humanos y legislación de IA a través de un bufete externo contratado.",
    "undp-org-readiness-OR-16-0": "Se proporcionan recursos actualizados sobre mejores prácticas en IA y derechos humanos a través de la intranet corporativa.",
    "undp-planning-PS-01-0": "El propósito principal del sistema — verificación de identidad biométrica para control de acceso físico — está documentado en la ficha técnica.",
    "undp-planning-PS-09-0": "La cadena de responsabilidad desde el desarrollador del modelo hasta el operador del sistema está documentada en el acuerdo de despliegue.",
    "undp-rights-mapping-HRM-02-0": "Se ha evaluado el impacto potencial sobre la dignidad humana: el sistema trata datos biométricos con garantías de privacidad reforzadas.",
    "undp-rights-mapping-HRM-03-0": "Se ha evaluado el impacto sobre la no discriminación: pruebas de sesgo demográfico realizadas trimestralmente con métricas de equidad.",
    "undp-rights-mapping-HRM-04-0": "Se ha evaluado el impacto sobre el derecho a la vida: el sistema no afecta directamente a este derecho; riesgo clasificado como bajo.",
    "undp-rights-mapping-HRM-05-0": "Se ha evaluado el impacto sobre la libertad frente a la esclavitud: no se identifican riesgos; el sistema no implica trabajo forzado.",
    "undp-rights-mapping-HRM-07-0": "Se ha evaluado el impacto sobre el derecho a la privacidad: alto impacto por procesamiento biométrico, mitigado con cifrado y minimización.",
    "undp-rights-mapping-HRM-08-0": "Se ha evaluado el impacto sobre el derecho a la propiedad: riesgo bajo; las plantillas biométricas no constituyen propiedad transferible.",
    "undp-rights-mapping-HRM-10-0": "Se ha evaluado el impacto sobre la libertad de expresión: riesgo bajo; el sistema no monitoriza comunicaciones ni contenido expresivo.",
    "undp-rights-mapping-HRM-11-0": "Se ha evaluado el impacto sobre la libertad de movimiento: riesgo medio; se mitiga con acceso alternativo por tarjeta de emergencia.",
    "undp-rights-mapping-HRM-12-0": "Se ha evaluado el impacto sobre la libertad de reunión: riesgo bajo; el sistema no rastrea agrupaciones ni patrones de reunión.",
    "undp-rights-mapping-HRM-14-0": "Se ha evaluado el impacto sobre el derecho al matrimonio y la familia: no se identifican riesgos relevantes para este derecho.",
    "undp-rights-mapping-HRM-16-0": "Se ha evaluado el impacto sobre el derecho a la educación: riesgo insignificante; el sistema opera exclusivamente en entornos laborales.",
    "undp-rights-mapping-HRM-17-0": "Se ha evaluado el impacto sobre el derecho a la seguridad social: no se identifican riesgos; el sistema no afecta prestaciones sociales.",
    "undp-rights-mapping-HRM-19-0": "Se ha evaluado el impacto sobre el derecho al trabajo: riesgo medio; fallos de reconocimiento podrían impedir el acceso al puesto de trabajo.",
    "undp-rights-mapping-HRM-20-0": "Se ha evaluado el impacto sobre el derecho al descanso: riesgo bajo; el sistema no monitoriza horas de trabajo ni descansos.",
    "undp-rights-mapping-HRM-22-0": "Se ha evaluado el impacto sobre los derechos de los menores: no aplica; el sistema solo procesa datos de empleados adultos.",
    "undp-rights-mapping-HRM-23-0": "Se ha evaluado el impacto sobre la libertad frente a la tortura: no se identifican riesgos; el sistema no causa sufrimiento físico.",
    "undp-rights-mapping-HRM-26-0": "Se ha evaluado el impacto sobre el acceso a la justicia: se garantiza un mecanismo de reclamación accesible para decisiones de acceso erróneas.",
    "undp-rights-mapping-HRM-27-0": "Se ha evaluado el impacto sobre la libertad frente a la detención arbitraria: riesgo insignificante en el contexto de acceso a edificios.",
    "undp-rights-mapping-HRM-28-0": "Se ha evaluado el impacto sobre el derecho a un juicio justo: no aplica directamente; existe un procedimiento de apelación interno.",
    "undp-rights-mapping-HRM-29-0": "Se ha evaluado el impacto sobre la presunción de inocencia: las denegaciones de acceso no implican acusación alguna.",
    "undp-rights-mapping-HRM-30-0": "Se ha evaluado el impacto sobre el derecho a recurso legal: existe un procedimiento formal de reclamación con resolución en 48 horas.",
    "undp-rights-mapping-HRM-31-0": "Se ha evaluado el impacto sobre el derecho de asilo: no se identifican riesgos; el sistema no se utiliza en contextos migratorios.",
    "undp-rights-mapping-HRM-32-0": "Se ha evaluado el impacto sobre el derecho a la nacionalidad: no se identifican riesgos; la verificación no depende de la nacionalidad.",
    "undp-rights-mapping-HRM-35-0": "Se han identificado los tribunales de derechos humanos y organismos de supervisión relevantes en las jurisdicciones de despliegue de la UE.",
    "undp-data-diligence-DD-02-0": "Se obtuvo consentimiento explícito e informado de cada empleado antes del registro biométrico, conforme al RGPD Artículo 9.",
    "undp-data-diligence-DD-11-0": "El rendimiento del sistema se mide y documenta: tasa de aceptación correcta del 99,2% y tasa de falso rechazo del 0,8%.",
    "undp-data-diligence-DD-13-0": "Se mantiene una ficha del modelo (Model Card) que documenta arquitectura, datos de entrenamiento, métricas de rendimiento y limitaciones conocidas.",
    "undp-data-diligence-DD-15-0": "La supervisión humana es obligatoria: los operadores de seguridad pueden anular decisiones del sistema en tiempo real.",
    "undp-data-diligence-DD-16-0": "Existe un proceso de monitorización post-despliegue con revisiones mensuales de rendimiento y actualizaciones trimestrales del modelo.",
    "undp-risk-analysis-RA-06-0": "Se ha calculado la severidad global utilizando la matriz Gravedad × Esfuerzo para cada derecho afectado identificado.",
    "undp-risk-management-RMG-03-0": "Las medidas de mitigación abordan tanto la probabilidad (mejoras técnicas) como la severidad (procedimientos de recurso y compensación).",
    "undp-risk-management-RMG-04-0": "Se ha establecido un cronograma de implementación: medidas técnicas en 3 meses, procedimentales en 6 meses, de gobernanza en 12 meses.",
    "undp-risk-management-RMG-05-0": "Se ha asignado un responsable para cada medida: el CISO para medidas técnicas, el DPO para privacidad y legal para procedimientos de recurso.",
    "undp-risk-management-RMG-07-0": "Se ha recalculado la probabilidad residual tras la implementación de medidas: reducida de Alta a Baja para todos los derechos afectados.",
    "undp-risk-management-RMG-08-0": "Se ha recalculado la severidad residual: reducida de Alta a Media gracias a los mecanismos de recurso y compensación establecidos.",
    "undp-risk-management-RMG-09-0": "Se ha documentado el impacto residual global: riesgo aceptable con medidas de mitigación activas y monitorización continua.",
    "undp-risk-management-RMG-10-0": "Se ha evaluado la aceptabilidad del riesgo residual: clasificado como aceptable por el comité de ética con revisión semestral.",
    "undp-risk-management-RMG-13-0": "Se registran todos los criterios de escala utilizados y la justificación de los rangos aplicados en cada evaluación de riesgo.",
    "undp-risk-management-RMG-14-0": "Todas las aportaciones de las partes interesadas están documentadas, incluyendo consultas con empleados y representantes sindicales.",
    "undp-monitoring-MI-03-0": "Se implementa detección de deriva del modelo mediante comparación mensual de distribuciones de puntuación de confianza con la línea base.",
    # ── Environmental Impact: Energy & Carbon ───────────────────────────
    "env-energy-carbon-EC-01-0": "El consumo energético total del entrenamiento del modelo se ha medido y documentado: 450 kWh para el último ciclo de entrenamiento.",
    "env-energy-carbon-EC-01-1": "La infraestructura de entrenamiento utiliza un 72% de energía renovable (eólica y solar) según el mix del centro de datos contratado.",
    "env-energy-carbon-EC-02-0": "El consumo energético de inferencia se monitoriza continuamente: cada servidor consume ~0,8 kWh por hora de operación.",
    "env-energy-carbon-EC-02-1": "Se monitorizan métricas de energía por solicitud: ~0,003 kWh por decisión de acceso en promedio.",
    "env-energy-carbon-EC-03-0": "Se ha estimado la huella de carbono del sistema utilizando la metodología del GHG Protocol: 2,1 toneladas de CO₂e anuales por sede.",
    "env-energy-carbon-EC-03-1": "Se consideran las emisiones de Alcance 1, 2 y 3, incluyendo la fabricación de hardware y el transporte de equipos.",
    "env-energy-carbon-EC-04-0": "Se han establecido objetivos de reducción de la huella de carbono: 15% de reducción anual mediante optimización de modelos y hardware.",
    "env-energy-carbon-EC-04-1": "El progreso respecto a los objetivos de reducción de carbono se revisa semestralmente con el comité de sostenibilidad.",
    "env-energy-carbon-EC-05-0": "El 72% de la energía consumida por el sistema proviene de fuentes renovables certificadas.",
    "env-energy-carbon-EC-05-1": "Existe un compromiso de alcanzar el 90% de energía renovable para 2027 mediante contratos con centros de datos verdes.",
    "env-energy-carbon-EC-06-0": "No se utiliza compensación de carbono actualmente; la estrategia prioriza la reducción directa de emisiones.",
    # ── Environmental Impact: Hardware ──────────────────────────────────
    "env-hardware-HW-01-0": "Se ha considerado el impacto ambiental de las GPUs seleccionadas (NVIDIA T4), priorizando eficiencia energética para inferencia.",
    "env-hardware-HW-01-1": "Se priorizan opciones de hardware energéticamente eficientes: GPUs de inferencia de bajo consumo en lugar de GPUs de entrenamiento.",
    "env-hardware-HW-02-0": "Se monitorizan las tasas de utilización de hardware: las GPUs operan al 65% de capacidad media durante horario laboral.",
    "env-hardware-HW-02-1": "Se aplica planificación de cargas de trabajo: reentrenamientos programados en horas valle para maximizar la eficiencia.",
    "env-hardware-HW-03-0": "Los ciclos de renovación de hardware se planifican cada 5 años, equilibrando rendimiento y sostenibilidad ambiental.",
    "env-hardware-HW-03-1": "Se considera la reutilización y donación de hardware retirado a instituciones educativas antes de su reciclaje.",
    "env-hardware-HW-04-0": "El hardware al final de su vida útil se gestiona a través de programas certificados de reciclaje de residuos electrónicos.",
    "env-hardware-HW-04-1": "Los materiales peligrosos de los componentes de hardware se rastrean y gestionan conforme a la normativa RoHS/RAEE.",
    "env-hardware-HW-05-0": "Los proveedores de hardware se evalúan por sus prácticas medioambientales y compromisos de sostenibilidad documentados.",
    # ── Environmental Impact: Data Management ───────────────────────────
    "env-data-management-DM-01-0": "Se optimizan las prácticas de almacenamiento con compresión de imágenes, almacenamiento escalonado y deduplicación de plantillas.",
    "env-data-management-DM-01-1": "La política de retención elimina imágenes de registro tras la generación del embedding, reduciendo el almacenamiento necesario.",
    "env-data-management-DM-02-0": "Se minimiza la transferencia de datos mediante procesamiento local en cada sede, evitando transferencias masivas entre centros.",
    "env-data-management-DM-02-1": "Se ha considerado el coste ambiental de las transferencias de datos para sincronización de modelos entre sedes.",
    "env-data-management-DM-03-0": "Los centros de datos se seleccionan por criterios ambientales: PUE <1,3, uso de refrigeración por agua y energía renovable.",
    "env-data-management-DM-03-1": "Se ha priorizado la ubicación de centros de datos en países nórdicos de la UE por sus climas fríos y alta disponibilidad de renovables.",
    "env-data-management-DM-04-0": "El uso de agua de los sistemas de refrigeración se mide y documenta: 0,5 litros por kWh consumido en el centro de datos.",
    "env-data-management-DM-04-1": "Se emplean tecnologías de refrigeración eficiente en agua, incluyendo free cooling durante los meses más fríos.",
    # ── Environmental Impact: Model Efficiency ──────────────────────────
    "env-model-efficiency-ME-01-0": "El tamaño del modelo (25 millones de parámetros) está justificado frente a los requisitos de precisión del reconocimiento facial.",
    "env-model-efficiency-ME-01-1": "Se evaluaron modelos más pequeños (MobileNet, EfficientNet) antes de seleccionar ResNet-50 por su equilibrio precisión-eficiencia.",
    "env-model-efficiency-ME-02-0": "Se aplican técnicas de entrenamiento eficientes: transfer learning desde un modelo preentrenado, mixed precision y early stopping.",
    "env-model-efficiency-ME-02-1": "El número de ejecuciones de entrenamiento (12 experimentos) está documentado y justificado por la búsqueda de hiperparámetros.",
    "env-model-efficiency-ME-03-0": "Se aplican técnicas de optimización de inferencia: cuantización INT8, pruning y caché de embeddings de empleados frecuentes.",
    "env-model-efficiency-ME-03-1": "Se ha evaluado explícitamente el equilibrio entre precisión del modelo y coste computacional, documentando la decisión tomada.",
    "env-model-efficiency-ME-04-0": "El calendario de reentrenamiento se basa en métricas de degradación del rendimiento, no en intervalos fijos predeterminados.",
    "env-model-efficiency-ME-04-1": "Se utilizan enfoques de fine-tuning incremental en lugar de reentrenamiento completo cuando es posible.",
    "env-model-efficiency-ME-05-0": "Se monitorizan métricas de eficiencia ambiental: precisión por vatio y decisiones por kWh junto con las métricas de rendimiento.",
    # ── Environmental Impact: Lifecycle ──────────────────────────────────
    "env-lifecycle-LC-01-0": "Se ha realizado una evaluación del ciclo de vida que cubre desde el desarrollo hasta el desmantelamiento del sistema.",
    "env-lifecycle-LC-01-1": "Las emisiones incorporadas por la fabricación de hardware (GPUs, cámaras, servidores) se incluyen en la evaluación del ciclo de vida.",
    "env-lifecycle-LC-02-0": "Existe un plan documentado para el desmantelamiento ambientalmente responsable del sistema y su infraestructura.",
    "env-lifecycle-LC-02-1": "El plan de desmantelamiento aborda la eliminación de datos biométricos, la gestión de hardware y la finalización de servicios.",
    "env-lifecycle-LC-03-0": "Los proveedores de servicios en la nube y terceros se evalúan por sus compromisos ambientales y publicación de informes.",
    "env-lifecycle-LC-03-1": "Los acuerdos de nivel de servicio incluyen criterios de rendimiento ambiental, como PUE máximo y porcentaje de renovables.",
    "env-lifecycle-LC-04-0": "Se aplican principios de economía circular a la infraestructura de IA: reutilización de GPUs, reparación de cámaras y reciclaje de servidores.",
    # ── Environmental Impact: Monitoring ─────────────────────────────────
    "env-monitoring-EM-01-0": "Se han definido KPIs ambientales para el sistema: energía por inferencia, carbono total anual y consumo de agua por sede.",
    "env-monitoring-EM-01-1": "Los KPIs ambientales se revisan y actualizan semestralmente con el comité de sostenibilidad de la organización.",
    "env-monitoring-EM-02-0": "Los datos de impacto ambiental se reportan a las partes interesadas internas en el informe anual de sostenibilidad.",
    "env-monitoring-EM-02-1": "El reporte ambiental sigue el estándar GRI para indicadores de energía y emisiones de gases de efecto invernadero.",
    "env-monitoring-EM-03-0": "Existe un proceso documentado para identificar e implementar mejoras ambientales basadas en los datos de monitorización.",
    "env-monitoring-EM-03-1": "Se capturan sistemáticamente las lecciones aprendidas de incidentes ambientales o deficiencias de rendimiento detectadas.",
    "env-monitoring-EM-04-0": "La organización cumple con las regulaciones ambientales aplicables a las operaciones de IA y centros de datos en la UE.",
    "env-monitoring-EM-05-0": "Los objetivos ambientales del sistema de IA están alineados con los compromisos de sostenibilidad más amplios de la organización.",
}
